### ISSUE TITLE
Publish the project in npm

### ISSUE THREAD

**Issue by gibatronic** [Sidnicious/noeol#1]
Hi there Sidney! This is such a simple but valuable solution.
Would you be interested in making this code available through the [npm](https://www.npmjs.com/) package manager? I could submit a pull request for it.

**Comment by s4y** [comment]
Hey! I wouldn't have considered publishing it on npm, but I see the appeal as multiplatform package manager. How would you do it, given that it's a C program? Yes, on the surface I'd accept that pull request.

**Comment by gibatronic** [comment]
Done. With a [`install`](https://docs.npmjs.com/misc/scripts) hook it's possible to run `make` to build the binary. Take a look and let me know if everything looks good!

**Comment by s4y** [comment]
Published. Thanks for the thorough PR! I had to make one small tweak to the package.json (`install` → `preinstall`).
